name: ci

on:
  push:
    paths-ignore:
      - "README.md"

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install dev dependencies
        run: pip install -r dev-requirements.txt
      - name: Run linter
        run: ruff check

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build micropython
        env:
          CFLAGS_EXTRA: "-DMICROPY_PY_OS_DUPTERM=2"  # os.dupterm support on unix
        run: |
          git clone -b v1.24-release --depth=1 --single-branch https://github.com/micropython/micropython.git
          cd micropython
          git submodule update --init
          make -C ports/unix
          cp ports/unix/build-standard/micropython /usr/local/bin/
          cd ..
          rm -rf micropython
      - name: Install test dependencies
        run: ./bin/setup
      - name: Install mosquitto
        run: sudo apt-get install -y mosquitto
      - name: Install the package dependencies
        run: "micropython -m mip install github:${{ github.repository }}@${{ github.ref_name }}"
      - name: Run tests
        run: micropython -m unittest
        env:
          MICROPYPATH: "${{ github.workspace }}:.frozen:~/.micropython/lib:/usr/lib/micropython:${{ github.workspace }}/tests/mocks"
      - name: Run integration tests
        run: ./bin/test_e2e
